### ISSUE TITLE
Issue endpoint is not support optional

### ISSUE THREAD

**Issue by Tona-Mangobyte** [chantouchsek/vue-axios-http#320]
@chantouchsek
![image](https://user-images.githubusercontent.com/55422610/162626875-8b0d5886-6c2f-4813-843a-3d9baa338a75.png)

**Comment by chantouchsek** [comment]
I don't really get your concern right now. will talk about this next week after Khmer New Year 😁😂.

**Comment by chantouchsek** [comment]
Release at [v2.0.1](https://github.com/chantouchsek/vue-axios-http/releases/tag/v2.0.1)
